apiVersion: v1
kind: Service
metadata:
  name: redis-golang
  labels:
    app: redis-golang
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: redis-golang
